fix pre-push

diff --git a/mate-scripts/configs/git-hooks/javascript/pre-push b/mate-scripts/configs/git-hooks/javascript/pre-push
--- a/mate-scripts/configs/git-hooks/javascript/pre-push
+++ b/mate-scripts/configs/git-hooks/javascript/pre-push
@@ -2,20 +2,16 @@
 
 PASS=true
 
-# ESLint
-STAGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM ./src | grep ".\(j\|t\)sx\{0,1\}$")
+# Tests
+echo "Testing javascript"
 
-if [[ "$STAGED_JS_FILES" != "" ]]; then
-  echo "Testing javascript"
+npx mate-scripts test
 
-  npx mate-scripts test
-
-  if [[ "$?" == 0 ]]; then
-    printf "\033[32mTests Passed\033[0m\n\n"
-  else
-    printf "\033[031mTests Failed\033[0m\n\n"
-    PASS=false
-  fi
+if [[ "$?" == 0 ]]; then
+  printf "\033[32mTests Passed\033[0m\n\n"
+else
+  printf "\033[031mTests Failed\033[0m\n\n"
+  PASS=false
 fi
 
 if ! ${PASS}; then
